apiVersion: v1
kind: Service
metadata:
  name: ping-svc
spec:
  type: ClusterIP
  clusterIP: None
  selector:
    app: ping

---
apiVersion: v1
kind: Service
metadata:
  name: ext-ping-svc
spec:
  type: NodePort
  selector:
    app: ping
  ports:
  - name: http
    nodePort: 32000
    port: 4000
    targetPort: 4000