apiVersion: v1
kind: Service
metadata:
  name: pong-svc
spec:
  type: ClusterIP
  clusterIP: None
  selector:
    app: pong

---
apiVersion: v1
kind: Service
metadata:
  name: ext-pong-svc
spec:
  type: NodePort
  selector:
    app: pong
  ports:
  - name: http
    nodePort: 32100
    port: 4000
    targetPort: 4000